server:
  port: 6966


grpc:
  port: 6969
  trust-store-path: /Users/hamma/work/projects/gRPC/server/src/main/resources/server.jks
  trust-store-password: hamma123


logging:
  config:
    classpath: "logback.xml"