server:
  port: 6990

grpc:
  security:
    trust-store-path: /Users/hamma/work/projects/gRPC/server/src/main/resources/server.jks
    trust-store-password: hamma123

logging:
  config: "classpath:logback.xml"
